
export const ADD_PHOTO_SUCCESS = 'ADD_PHOTO_SUCCESS';
export const FETCH_PHOTO_SUCCESS = 'FETCH_PHOTO_SUCCESS';


export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const LOGOUT_USER = 'LOGOUT_USER';
